k_species = "species"
k_name = "name"
k_traits = "traits"
k_traits_max = "traits_max"
k_trait_rates_max = "trait_rates_max"
k_bounding_radius = "bounding_radius"
k_speed = "speed"
k_value = "value"
k_mp_index = "mp_index"

k_robots = "robots"
k_initial_battery_level = "initial_battery_level"
k_initial_trait_levels = "initial_trait_levels"
k_initial_configuration = "initial_configuration"
k_terminal_configuration = "terminal_configuration"
k_configuration_type = "configuration_type"
k_goal_type = "goal_type"
k_state_space_type = "state_space_type"
k_SE2 = "se2"
k_x = "x"
k_y = "y"
k_yaw = "yaw"

k_idle_current = "idle_current"
k_current_trait_functions_coeff = "current_trait_functions_coeff"
k_current_trait_rate_functions_coeff = "current_trait_rate_functions_coeff"
k_max_battery_capacity = "max_battery_capacity"
k_max_battery_rate = "max_battery_rate"
k_max_possible_current = "max_possible_current"
k_max_speed = "max_speed"
k_speed_coeff = "speed_coeff"
k_peukert_coeff = "peukert_coeff"
k_max_mass= "max_mass"

k_tasks = "tasks"
k_duration = "duration"
k_static_duration = "static_duration"
k_task_reward = "task_reward"
k_reward_time_decaying_rate = "reward_time_decaying_rate"
k_desired_traits = "desired_traits"
k_minimum_trait_rates = "minimum_trait_rates"
k_traits_summable = "traits_summable"
k_traits_dispensable = "traits_dispensable"
k_traits_depletable = "traits_depletable"
k_precedence_constraints = "precedence_constraints"
k_plan_task_indices = "plan_task_indicies"
k_finish_timepoint = "finish_timepoint"
k_start_timepoint = "start_timepoint"
k_predecessor = "predecessor"
k_successor = "successor"
k_solution = "solution"
k_statistics = "statistics"
k_task_trait_allocations = "task trait allocations"
k_makespan = "makespan"
k_total_time = "total_time"
k_computation_time = "computation_time"

k_num_robots = "num_robots"
k_num_tasks = "num_tasks"
k_num_traits = "num_traits"

k_alpha = "alpha"
k_gamma = "gamma"
k_dtas = "DTAS"
k_itags = "ITAGS"

k_nodes_generated= "nodes_generated"
k_nodes_evaluated = "nodes_evaluated"
k_nodes_expanded = "nodes_expanded"
k_nodes_pruned = "nodes_pruned"

k_robot_traits_matrix_reduction = "robot_traits_matrix_reduction"
k_reduction_types = "reduction_types"
k_summation = "summation"
k_minimum = "minimum"
k_maximum = "maximum"

k_deadline_constraints = "deadline_constraints"
k_deadlines = "deadlines"
k_deadline_type = "deadline_type"
k_absolute_deadline = "absolute_deadline"
k_relative_deadline = "relative_deadline"
k_start = "start"
k_completion = "completion"
k_timepoint = "timepoint"
k_timepoint_type = "timepoint_type"
k_task = "task"
k_bound = "bound"

k_motion_planners = "motion_planners"
k_environment_parameters = "environment_parameters"
k_config_type = "config_type"
k_ompl_environment_type = "ompl_environment_type"
k_use_data_dir = "use_data_dir"
k_yaml_filepath = "yaml_filepath"
k_algorithm_parameters = "algorithm_parameters"
k_ompl_mp_algorithm = "ompl_mp_algorithm"
k_timeout = "timeout"
k_simplify_path = "simplify_path"
k_simplify_path_timeout = "simplify_path_timeout"

k_itags_parameters= "itags_parameters"
k_dtas_parameters = "dtas_parameters"
k_has_timeout = "has_timeout"
k_timer_name = "timer_name"
k_alpha = "alpha"
k_beta = "beta"
k_prune_before_eval = "prune_before_eval"
k_save_pruned_nodes = "save_pruned_nodes"
k_save_closed_nodes = "save_closed_nodes"

k_scheduler_parameters = "scheduler_parameters"
k_scheduler_type = "scheduler_type"
k_milp_scheduler_type = "milp_scheduler_type"
k_milp_timeout = "milp_timeout"
k_thread = "threads"
k_compute_transition_duration_heuristic = "compute_transition_duration_heuristic"
k_use_hierarchical_objective = "use_hierarchical_objective"

k_best_first_search_parameters = "BestFirstSearchParameters"
k_dtas_milp_scheduler_paramters = "dtasMilpSchedulerParameters"
k_milp = "milp"
k_deterministic = "deterministic"
k_ompl = "ompl"
k_state = "state"
k_ompl_motion_planner_parameters = "OmplMotionPlannerParameters"
k_pgm = "pgm"
k_prm = "prm"
k_dtas = "dtas"
k_itags = "itags"
k_pgm_ompl_environment = "PgmOmplEnvironment"
k_ompl_motion_planner = "OmplMotionPlanner"
k_trait_distribution_parameters = "trait_distribution_parameters"
k_TASK = "TASK"
k_json = ".json"

k_configuration = "Configuration"
